### ISSUE TITLE
Harden injection

### ISSUE THREAD

**Issue by originell** [markdalgleish/bespoke-remote-prototype#2]
As correctly pointed out by @markdalgleish on twitter

> @originell Any thoughts on how we could make connect-bespoke-remote unaware of connect-livereload? The relationship seems a bit brittle atm

It really is. It overwrites the inject/write methods to be sure to really be in there. On the one hand that's good, because it's a real guarantee.. on the other hand it makes any other middleware that might want to inject stuff look hacky.

The [hack to avoid livereload injected into the remote template](https://github.com/markdalgleish/bespoke-remote-prototype/blob/master/bespoke-remote/index.js#L88) might actually not be necessary.. Maybe livereload is actually also nice to have while developing your own remote, though in "presentation mode" it is not necessary anymore.

To be honest I currently don't have _any_ good idea.. The current replace method might also be pretty slow on big presentations HTMLs I guess.

**Comment by markdalgleish** [comment]
I've started experimenting with adding our middleware before LiveReload. If I get that working, I'll try to make sure they work in either order, and in isolation, so that there's no dependency on LiveReload.

**Comment by originell** [comment]
Mh… Since it's javascript anyway and we have our own HTTP server running anyway (port 8001)… Maybe we should just inject some kind of loader script. That would bypass the one livereload is running in.

Oh nice! Excited to see what you push :)

**Comment by markdalgleish** [comment]
Wow, okay. This is much harder than I thought. The way connect-livereload works is an almighty hack, and one that can't be done twice to the same response, it seems. Not without a greater hack, at least.

Maybe we need to find a more minimal solution? Maybe more like Socket.io, where we require you to manually insert a script. If we set up a 'dev' flag when running a local server, we could easily exclude it from the final static version of your deck.

**Comment by markdalgleish** [comment]
What do you think, @originell?

**Comment by originell** [comment]
Oh man.. I hoped you would find some magic key :-S

Well, I guess the cleanest solution then is to write a loader script that takes socket.io + the bespoke-remote and injects them. I guess people would then have to insert that manually.

However I'd rather have this problem solved on a broader level… As far as I understand it, connect currently does not offer a standard way to do such "injections" in a clean way. It might be nice to actually offer a framework for that.. so f.e. making a connect middleware that offers a nice way for injection to happen (and then forking connect-livereload and hoping that the developer loves it and merges ;D). What do you think about that? Still not sure in what way that might work (if that is at all possible), but I think I will spend some brain-cycles on this.

Meanwhile I guess the injection is the easiest "workaround"

**Comment by markdalgleish** [comment]
I actually had the exact same idea, re: some higher level injection middleware that both bespoke-remote and livereload talk to. That's probably a little out of scope atm, but definitely something that's worth a look.

For now, we could write something a little less magical, especially since we have generator-bespoke to do the hard work of setting it up for everyone.

Eventually, we could shift all the manual work into some injecting middleware, but for now we'll just wire it up by hand. Something like this semi-psuedocode:

``` html
<script src="socket.io.js"></script>
<script src="bespoke.js"></script>
<script src="bespoke-remote.js"></script>
<script>
bespoke.horizontal.from('article', {
  remote: 'http://localhost:8001'
});
</script>
```

**Comment by markdalgleish** [comment]
So I managed to inject the remote script completely via middleware using connect-injector, and it works with connect-livereload. It even injects 'remote: true' into the plugins object in main.js. It's definitely not perfect and needs to be strengthened a bit, but it's working! :D

**Comment by originell** [comment]
Holy smokes :dancers:  :D That's friggin superduper :> need to look at this now :)

**Comment by originell** [comment]
From my perspective this seems to be fixed now? What do you say?

**Comment by markdalgleish** [comment]
Yep, closed :)
