### ISSUE TITLE
Add Remote Indicator

### ISSUE THREAD

**Issue by originell** [markdalgleish/bespoke-remote-prototype#3]
Currently we only output into the JS console if a remote connected/reconnected successfully.. It might be cool to have this as an overlay (OSX like but a bit more decent)

**Comment by markdalgleish** [comment]
The idiomatic way to do this in Bespoke.js would be to add an empty indicator div and change its classes so that presentation authors can style it themselves.

We might include a sensible default style with the generator, though.

**Comment by originell** [comment]
Awesome :) would it be OK to include two svgs (a "paired" and "unpaired" icon)? or is that too much in your opinion?
it's really just a matter of ~~your preference~~how idiomatic you see this, one can do a hell lot with css only :)

**Comment by markdalgleish** [comment]
Generally, I like that bespoke is completely unopinionated about styles. It's very easy to make that div a coloured circle using classes + border radius :)

**Comment by originell** [comment]
Ha good reminder.. that's actually why I chose it instead of any other presentation framework.

**Comment by markdalgleish** [comment]
I started work on this, should have something for you within the next 24 hours :)

**Comment by originell** [comment]
oh how cool :D

**Comment by markdalgleish** [comment]
Even though this issue is closed, there's plenty of room for improvement.
