### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by originell** [markdalgleish/bespoke-remote-prototype#5]
So while I was just thinking about something for the indicator, I stumbled upon the whole [timeout/heartbeat settings for socket.io](https://github.com/LearnBoost/Socket.IO/wiki/Configuring-Socket.IO).

Since `bespoke-remote` is used during presentations, I guess it would make sense to set a lower `close timeout`, `heartbeat interval` and `heartbeat timeout` so we can detect a disconnected remote fairly quickly?

What do you think about that?

**Comment by originell** [comment]
Note: I only mean to change the heartbeat for the remote client, not for every client. I guess it doesn't make sense to increase them for ever connected "primary screen". Especially since the most important one (presentation laptop) is usually connected via localhost anyway.

**Comment by markdalgleish** [comment]
Yep, that sounds like a good idea to me.

**Comment by originell** [comment]
Ok I just found out that you can't do it on a per-socket basis, only on the shared global `io` object. Which imo is not a good idea haha. I will however lower the times a bit from their defaults.
